#! /usr/bin/env python3
# -*- mode: Python; -*-

import sys

from librel.args import trans_main
from librel.relfrom import parsearguments, main

if __name__ == '__main__':
    trans_main(parsearguments(sys.argv[1:]), main)
