#! /usr/bin/env python3
# -*- mode: Python; -*-

import sys

from libvrt.args import transput
from libvrt.tools.hrt_check_tags import parsearguments, main

if __name__ == '__main__':
    # text mode both ways, so input has to be UTF-8
    transput(parsearguments(sys.argv[1:]), main)
