#! /usr/bin/env python3
# -*- mode: Python; -*-

import sys

from libvrt.args import transput
from libvrt.tools.hrt_s24_2020 import parsearguments, main

if __name__ == '__main__':
    # csv.reader requires text mode input so text it is
    transput(parsearguments(sys.argv[1:]), main)
