#! /usr/bin/env python3
# -*- mode: Python; -*-

from sys import argv

from libvrt.args import transput
from libvrt.tools.hrt_norm_lines import parsearguments, main

transput(parsearguments(argv[1:]), main,
         in_as_text = True,
         out_as_text = True)
