#! /usr/bin/env python3
# -*- mode: Python; -*-

import sys

from libvrt.args import multiput
from libvrt.tools.hrt_stat import parsearguments, main

if __name__ == '__main__':
    multiput(parsearguments(sys.argv[1:]), main)
