#! /usr/bin/env python3
# -*- mode: Python; -*-


"""
vrt-sort

Sort text structures within VRT input by creating a sort key from text
attribute values and using the Unix sort command to sort according to the key.

The actual implementation is in libvrt.tools.vrt_sort.py
"""


from libvrt.tools.vrt_sort import VrtSorter


if __name__ == '__main__':
    VrtSorter().run()
