#! /usr/bin/env python3
# -*- mode: Python; -*-


"""
vrt-add-struct-attrs

Add structural attribute annotations to VRT from a TSV file.

The actual implementation is in libvrt.tools.vrt_add_struct_attrs.
"""


from libvrt.tools.vrt_add_struct_attrs import StructAttrAdder


if __name__ == '__main__':
    StructAttrAdder().run()
