#! /usr/bin/env python3
# -*- mode: Python; -*-

from sys import argv

from libvrt.args import transput
from libvrt.tools.vrt_fix_no_space import parsearguments, main

transput(parsearguments(argv[1:]), main,
         in_as_text = False,
         out_as_text = False)
