#! /usr/bin/env python3
# -*- mode: Python; -*-

from libvrt.args import transput
from libvrt.tools.vrt_drop import parsearguments, main

transput(parsearguments(), main,
         in_as_text = False,
         out_as_text = False)
