#! /usr/bin/env python3
# -*- mode: Python; -*-

import os, sys

from libvrt.args import multiput2
from libvrt.tools.vrt_partition import parsearguments, main

multiput2(parsearguments(sys.argv[1:]),
          main,
          in_as_text = False)
