#! /usr/bin/env python3
# -*- mode: Python; -*-


"""
vrt-select

A VRT tool to select (keep or drop) structures (elements) with
attribute values matching specified regular expressions in VRT input.

The actual implementation is in libvrt.tools.vrt_select.
"""


from libvrt.tools.vrt_select import StructSelect


if __name__ == '__main__':
    StructSelect().run()
