#! /usr/bin/env python3
# -*- mode: Python; -*-

import sys

from libvrt.args import transput
from libvrt.tools.vrt_sample_tokens import parsearguments, main

if __name__ == '__main__':
    transput(parsearguments(sys.argv[1:]), main,
             in_as_text = False,
             out_as_text = False)
