#! /usr/bin/env python3
# -*- mode: Python; -*-


"""
vrt-update-attrs

Update or add structural attribute annotations to VRT from a TSV file
or with a fixed or computed value.

The actual implementation is in libvrt.tools.vrt_update_attrs.
"""


from libvrt.tools.vrt_update_attrs import AttrUpdater


if __name__ == '__main__':
    AttrUpdater().run()
