#! /usr/bin/env python3
# -*- mode: Python; -*-

"""
vrt-extract-seed

A VRT tool to extract words (word forms) from VRT input for a random
number generator seed.

The actual implementation is in libvrt.tools.vrt_extract_seed.
"""


from libvrt.tools.vrt_extract_seed import SeedExtractor


if __name__ == '__main__':
    SeedExtractor().run()
