#! /usr/bin/env python3
# -*- mode: Python; -*-

import sys

from libvrt.args import transput
from libvrt.tools.vrt_from_sparv_xml import parsearguments, main

if __name__ == '__main__':
    transput(parsearguments(sys.argv[1:]), main)
