#! /usr/bin/env python3
# -*- mode: Python; -*-

import os, sys

from libvrt.args import transput
from libvrt.tools.vrt_fix_nertag import parsearguments, main

transput(parsearguments(),
         main,
         in_as_text = False,
         out_as_text = False)
