#! /usr/bin/env python3
# -*- mode: Python; -*-

from itertools import groupby, count
from queue import Queue
from subprocess import Popen, PIPE
from threading import Thread
import enum, os, re, sys, traceback

from vrtargslib import trans_args, trans_main
from vrtargslib import BadData, BadCode

from vrtnamelib import binxname, binxrest
from vrtnamelib import isbinnames as isnames
from vrtnamelib import binnamelist as namelist, nameindex, nameindices
from vrtnamelib import bininsertnames as insertnames

from vrtdatalib import binasrecord as asrecord
from vrtdatalib import binescape as escape, binunescape as unescape

from outsidelib import ALMARMOTCMD

def parsearguments():
    description = '''

    Pass word forms and specially prepared features in a flat vrt
    document through MarMoT tagger using the model from the alpha
    version of the Turku dependency parser. Insert the new tags and
    features in new fields after the input feature field. The vrt
    document must have position names before any content. (A "flat"
    vrt document has no markup or comment lines inside sentence
    elements.)

'''
    parser = trans_args(description = description)
    parser.add_argument('--word', '-w', metavar = 'name',
                        type = binxname, default = b'word',
                        help = 'input word field name (default word)')
    parser.add_argument('--tag', '-t', metavar = 'name',
                        type = binxname, default = b'marmot.in',
                        help = 'input tag field name (default marmot.in)')

    # so the defaults are not valid values of the type?
    parser.add_argument('--prefix', '-p', metavar = 'fix',
                        type = binxname, default = b'',
                        help = 'prefix to output field names')
    parser.add_argument('--suffix', '-s', metavar = 'fix',
                        type = binxrest, default = b'',
                        help = 'suffix to output field names')

    args = parser.parse_args()
    args.prog = parser.prog
    return args

def message(args, mess):
    print(args.prog + ':', mess, file = sys.stderr)

def terminate(proc):
    try:
        proc.terminate()
    except ProcessLookupError:
        pass

def main(args, inf, ouf):

    with Popen(ALMARMOTCMD,
               stdin = PIPE,
               stdout = PIPE,
               stderr = sys.stderr.buffer) as marmot:

        copy = Queue()
        Thread(target = combine, args = (args, marmot, copy, ouf)).start()

        status = 1
        try:
            implement_main(args, inf, marmot, copy)
            status = 0
        except BadData as exn:
            message(args, exn)
        except BrokenPipeError as exn:
            message(args, 'broken pipe in main thread')
        except KeyboardInterrupt as exn:
            message(args, 'keyboard interrupt in main thread')
        except Exception as exn:
            print(traceback.format_exc(), file = sys.stderr)

        if status:
            terminate(marmot)
        else:
            marmot.stdin.close()

        try:
            copy.join()
        except KeyboardInterrupt:
            message(args, 'keyboard interrupt in main thread')
            status = 1

        return status

def implement_main(args, inf, marmot, copy):

    # each "word" and "tag" go to marmot, with an empty line after
    # each sentence; everything goes to copy alternative groups of
    # meta and data, with new "marmot.pos", "marmot.feat" (or such) in
    # names

    wordix, posix = None, None

    def send(sentence):
        for record in sentence:
            marmot.stdin.write(unescape(record[wordix]))
            marmot.stdin.write(b'\t')
            marmot.stdin.write(unescape(record[posix]))
            marmot.stdin.write(b'\n')
        else:
            marmot.stdin.write(b'\n')
            marmot.stdin.flush()

    def setnames(line):
        nonlocal wordix, posix
        if isnames(line):
            wordix, posix = nameindices(namelist(line), args.word, args.tag)
            return insertnames(line, args.tag,
                               args.prefix + b'marmot.pos' + args.suffix,
                               args.prefix + b'marmot.feat' + args.suffix)
        return line

    def issome(line): return not line.isspace()
    def ismeta(line): return line.startswith(b'<')

    first = True
    for groupismeta, group in groupby(filter(issome, inf), ismeta):

        if groupismeta:
            meta = tuple(map(setnames, group))
            copy.put(meta)
            first = False
            continue

        # groupisdata

        if first:
            # there shall always be previous meta
            copy.put(())
            first = False

        if wordix is None:
            raise BadData('error: token before field names')

        sentence = tuple(map(asrecord, group))
        copy.put(sentence)
        send(sentence)

    if not groupismeta:
        # there shall always be final meta
        copy.put(())

def combine(args, marmot, copy, out):
    '''Read marmot output (id TAB word TAB _ TAB pos ... msd TAB NL / NL)
    and flat vrt from the copy process. Insert tags from marmot to the
    vrt at the named position.

    This is run as a thread that consumes the marmot process and syncs
    it with the copy queue. Preceding meta and corresponding data were
    put in the queue before the data was sent to marmot, so they will
    always be there when a sentence is read out of marmot.

    '''

    fail = True
    try:
        implement_combine(args, marmot, copy, out)
        fail = False
    except BrokenPipeError:
        message(args, 'broken pipe in combine thread')
    except StopIteration:
        # not sure when this can happen now
        message(args, 'stop iteration in combine thread')
    except ValueError as exn:
        # sometimes keyboard interruption in main thread produces here
        # a readline of closed file (or at least it did in one stage
        # in development)
        message(args, 'value error in combine thread ' + str(exn))
    finally:
        if fail: terminate(marmot)

def implement_combine(args, marmot, copy, out):
    '''Thread may find pipe closed.'''

    response = (tokens
                for isempty, tokens
                in groupby(marmot.stdout, bytes.isspace)
                if not isempty)

    at = None # marmot.in field index, after which insert new
    for analyses in response:

        meta = copy.get_nowait()
        data = copy.get_nowait()
        copy.task_done()
        copy.task_done()

        for line in meta:
            if isnames(line):
                at = nameindex(namelist(line), args.tag)

        if at is None:
            raise BadData('combine thread: data before names')

        shipmeta(meta, out)
        for new, old in zip(analyses, data):
            [
                # http://ufal.mff.cuni.cz/
                # conll2009-st/task-description.html
                # ID FORM LEMMA PLEMMA POS PPOS FEAT PFEAT
                # HEAD PHEAD DEPREL PDEPREL FILLPRED PRED APREDs
                # but MarMoT truncates at eight fields
                # https://github.com/muelletm/cistern/blob/wiki/marmot.md
                # (actual produced ID is 1-based as it should)
                ID, form, lemma, plemma,
                pos, ppos, feat, pfeat
            ] = asrecord(new)
            old.insert(at + 1, escape(pfeat))
            old.insert(at + 1, escape(ppos))
        else:
            shipdata(data, out)

    # should this have a timeout? or could it be .get_nowait()?
    # added flush and made get get_nowait because a few processes
    # seemed to make no progress till they timed out - were they
    # stalled here?
    out.flush()
    shipmeta(copy.get_nowait(), out)
    copy.task_done()

def shipmeta(meta, out):
    for line in meta: out.write(line)

from datetime import datetime
def shipdata(data, out):
    if len(data) > 2000:
        # even marmot appeared to behave badly with long "sentences"
        # (though only much longer than the parser - present limit of
        # 2000 is taken out of thin air and could probably have been
        # much larger but then it only controls a warning in stderr)
        sys.stderr.buffer.write(b'shipping data at ')
        sys.stderr.buffer.write(datetime.now().isoformat().encode())
        sys.stderr.buffer.write(b' of len ')
        sys.stderr.buffer.write(str(len(data)).encode())
        sys.stderr.buffer.write(b'\n')
        sys.stderr.buffer.flush()
    for record in data:
        out.write(b'\t'.join(record))
        out.write(b'\n')

if __name__ == '__main__':
    trans_main(parsearguments(), main,
               in_as_text = False,
               out_as_text = False)
