# -*- coding: utf-8 -*-


P_ATTRS = lemma/ pos/

SRC_DIR = .
SRC_FILES = testcorp.vrt0 testcorp2.vrt0 testcorp3.vrt0

VRT_FIX_ATTRS_OPTS_EXTRA = --input-fields "word lemma pos" --output-fields "word lemma:set pos:set"

include ../corp-common.mk
