#! /bin/bash

# rel tools regression test
# runs each check/TOPIC.sh
# call in rel-tools/ like:
# $ check/regret
# $ check/regret TOPIC ...
#
# TOPIC is quietly ignored if not one of those below

declare -a target=("$@")

consider () {
    if test "${#target[@]}" = 0
    then
	bash "check/$1.sh"
    else
	for t in "${target[@]}"
	do
	    test "$1" = "$t" && bash "check/$t.sh"
	done
    fi
}

# consider foo => bash check/foo.sh
# if no target specified
# or foo is a target

consider cmp

consider from
consider rename

consider sort
consider order
consider shuffle

consider head
consider tail
consider sample

consider keep
consider keepc
consider drop
consider dropc

consider sum
consider union
consider meet
consider sans
consider symm

consider join
consider match
consider miss
consider image
consider compose2
