#! /bin/sh

# klk-retrieve-para-info
#
# Usage: klk-retrieve-para-info issue-zip-map.tsv output-dir
#                               [in.vrt | in.tsv]
#
# Retrieve paragraph information from KLK v1 ALTO files in zips under
# /corpora/digilib in IDA (frozen) by using
# klk-altozip-extract-para-info.
#
# Arguments:
# - issue-zip-map.tsv: A TSV file mapping from issues to zip files.
#   The file should contain two columns, separated by tabs: issue id
#   (of the form publid_date_issuenum) and zip file name relative to
#   /corpora/digilib in IDA.
# - output-dir: The directory to which to output paragraph info TSV
#   files.
# - in.vrt: A VRT file from which to first extract a list of files
#   (named in-filelist.tsv) and then paragraph information from the
#   corresponding zip files.
# - in.tsv: A TSV file containing a previously extracted list of
#   files: issue id and ALTO file base name (without .xml), separated
#   by a tab.
#
# If in.tsv or in.vrt is not specified, read VRT input from stdin.


LC_ALL=C

tab="$(printf "\t")"

module load ida

issue_zip_map=$1
output_dir=$2
shift 2

if [ "$1" = "" ] || [ "${1%.tsv}" == "$1" ]; then
    if [ "$1" = "" ]; then
        filelist=filelist.tsv
    else
        filelist=${1%.vrt}-filelist.tsv
    fi
    echo "Generating file list $filelist"
    grep -h '^<text' "$@" |
        grep -o ' img_url="[^"]*"' |
        perl -pe 's/^.*DIRECTORY#//; s/#SEPARATOR#/\t/; s/\.#EXTENSION#"//' |
        sort -k1,1 -k2,2 -t"$tab" > $filelist
else
    filelist="$@"
    echo "Using file list $filelist"
fi

ziplist=ziplist.tsv
zipdir=zips

mkdir -p $zipdir

cut -f1 $filelist |
    uniq |
    join -t"$tab" - $issue_zip_map |
    uniq > $ziplist

echo "Retrieving paragraph info"
echo "$(wc -l $ziplist) zip files to read"

i=1

cut -f2 $ziplist |
    while read zip; do
        year=$(echo $zip | cut -d/ -f3)
        local_zip=$zipdir/$(basename $zip)
        para_info_file=$output_dir/$(basename $zip .zip).tsv
        if [ -e "$para_info_file" ]; then
            echo "$para_info_file already exists; skipping"
        else
            ida download -f corpora/digilib/$zip $local_zip
            mkdir -p $output_dir
            ./klk-altozip-extract-para-info $local_zip > $para_info_file
            rm $local_zip
            echo "$i: $para_info_file"
        fi
        i=$((i + 1))
    done

echo "Done"
