#! /usr/bin/env python3
# -*- mode: Python; -*-

import sys

from librel.args import transput
from librel.tools.relshuffle import parsearguments, main

if __name__ == '__main__':
    transput(parsearguments(sys.argv[1:]), main)
