#! /usr/bin/env python3
# -*- mode: Python; -*-

'''Wrap plaintext (assumed UTF-8) in text and paragraph tags. Escape
&, <, >.

'''

import os, re, sys, tempfile, traceback

from itertools import groupby

from vrtargslib import trans_args, trans_main
from vrtdatalib import escape

def parsearguments():
    description = '''

    Wrap plaintext (assumed UTF-8) in text and paragraph tags. Escape
    any ampersand and angle brackets (less-than and greater-than
    signs) as the corresponding character entities.

    '''

    parser = trans_args(description = description, inplace = False)

    args = parser.parse_args()
    args.inplace = False
    args.backup = None
    args.prog = parser.prog
    return args

def main(args, ins, ous):
    def issome(line): return not line.isspace()

    groups = (group
              for kind, group
              in groupby(map(escape, ins), issome)
              if kind)

    first = next(groups, None)

    # there are to be no empty elements
    if first is None: return

    print('<text>', file = ous)
    ship(first, ous)
    for rest in groups: ship(rest, ous)
    print('</text>', file = ous)

def ship(para, ous):
    print('<paragraph>', file = ous)
    for line in para: print(line, end = '', file = ous)
    print('</paragraph>', file = ous)

if __name__ == '__main__':
    # consider it a win to crash now if not UTF-8
    # and not produce invalid output in that case
    trans_main(parsearguments(), main)
