#! /bin/bash

# multirun
#
# Run a processing command for multiple input files, possibly in
# parallel with the help of GNU Parallel or SLURM via game.

# TODO:
# - Handle subdirectories in the input: at least make
#   --output-file-pattern work with them.
# - Support protecting "{" in command (and --output-file-pattern).


progname=`basename $0`
progdir=`dirname $0`


# Default values for mode-specific options; the defaults for these in
# optspecs are "default" to be able to recognize if the option has
# been specified explicitly (setting the mode) or not
jobs_default="25%"
load_default="100%"
time_default="30"
memory_default="1024M"
scratch_default="0"
cores_default="1"

# Minimum values for game-specific options that support dynamic values
time_min=5
memory_min=1
scratch_min=0


usage_header="Usage: $progname [options] outdir \"command\" infiles ...

Run a processing command for multiple input files infiles, producing
output to output directory outdir, typically one output file
corresponding to one input file, possibly in parallel with the help of
GNU Parallel or SLURM via game.

command is a single string containing a complete command line with a
command and arguments. command is evaluated by the shell, so it can be
composed of multiple commands, use I/O redirection and pipes.

In the command line, the following strings are replaced with input or
output file names (including the directory): {<} -> input file name,
{<.} -> input file name without (the last) extension, {<..} -> input
file name without the last two extensions, {<.*} -> input file name
without any extensions (the \"<\" in these can be omitted); {>}, {>.},
{>..}, {>.*} -> the same for output file name; {/}, {/.}, {/..}, {/.*}
-> the same for the base (input) file name without directories. When
using Parallel (or game with Parallel available), its replacement
strings are also replaced, including the additional ones added by the
--plus option."

optspecs='
m|mode=MODE "default"
    Run command using MODE: one of "parallel" (use GNU Parallel),
    "game" (use SLURM via game) or "serial" (run serially); any prefix
    of the mode name is also recognized. Options specific to Parallel
    or game implicitly set the mode correspondingly. (Default:
    "parallel" if Parallel is available, otherwise "serial".)
output-file-pattern=PATTERN "{}" outfile_pattern
    If PATTERN matches any files in the output directory for an input
    file, do not run command for the input file. "{}" in PATTERN
    refers to the base name of the input file (without directories).
    Bash string operations can also be used to modify the base name of
    the input file: for example, "{%.*}" is the file name with the
    (last) extension removed and "{##*.}" is the last extension.
    Shell wildcards in PATTERN are expanded. NOTE that this option
    only specifies the files whose existence is to be checked for each
    input file; the names of the actual output files are determined by
    command. (Default: %(default)s.)
options=OPTS opts
    Pass OPTS as (additional) options to Parallel or game.
f|force
    Run the command even if the output file exists.
v|verbose
    Output the commands to be run.
n|dry-run
    Do not actually run commands; only show what is to be run.

@ Options specific to Parallel

j|jobs=NUM "default"
    Run up to NUM jobs in parallel. NUM can be a positive integer, a
    percentage (NUM%) of CPU threads, +NUM to add to the number of CPU
    threads or -NUM to subtract. (For other supported forms, please
    see the Parallel documentation.) (Default: '$jobs_default'.)
load=MAX-LOAD "default"
    Do not start jobs unless CPU load is below MAX-LOAD. The form of
    MAX-LOAD is the same as for NUM in --jobs. (Default:
    '$load_default'.)

@ Options specific to game (SLURM)

T|time=TIME "default"
    Reserve TIME time for each job, in minutes or hours:minutes,
    possibly relative to input file size (see the note below)
    (default: '$time_default').
M|memory=SIZE "default"
    Reserve SIZE memory (RAM) for each job; suffix SIZE with M
    (default) or G for mebi- and gibibytes, possibly relative to input
    file size (see the note below) (default: '$memory_default').
S|scratch=SIZE "default"
    Reserve SIZE gigabytes of fast local storage, possibly relative to
    input file size (see the note below) (default:
    '$scratch_default').
C|cores=NUM "default"
    Reserve NUM CPU cores for each job (default: '$cores_default').
'

usage_footer="The game-specific options --time, --memory and --scratch may specify
values relative to the size of the input file by appending a slash
followed by a positive integer, optionally suffixed by K, M (default)
or G for kibi-, mebi- or gibibytes, respectively. (k, m, g are also
recognized.) For example, --time=5/1G specifies reserving 5 minutes of
time for each 1 GiB of input file.

Note that the default values for game-specific options differ from the
defaults in game."


. $progdir/korp-lib.sh


# Process options
eval "$optinfo_opt_handler"

game=$progdir/../vrt-tools/game

opts_parallel="jobs load"
opts_game="time memory scratch cores"

has_parallel=$(prog_available parallel && echo 1)


check_outdir () {
    if [ ! -d "$outdir" ]; then
        if [ -e "$outdir" ]; then
            error "$outdir exists but is not a directory"
        fi
        if [ "$dry_run" = "" ]; then
            mkdir "$outdir"
        fi
    fi
}

check_mode_specific_opts () {
    local implicit_mode check_mode opt parallel_specific game_specific
    implicit_mode=
    for check_mode in parallel game; do
        for opt in $(eval echo \$opts_$check_mode); do
            if [ "$(eval echo \$$opt)" != "default" ]; then
                eval "${check_mode}_specific=\"\$${check_mode}_specific --$opt\""
                implicit_mode=$check_mode
            else
                eval "$opt=\$${opt}_default"
            fi
        done
    done
    if [ "$parallel_specific" != "" ] && [ "$game_specific" != "" ]; then
        error "Do not specify both Parallel-specific ($(delimit ', ' $parallel_specific)) and game-specific ($(delimit ', ' $game_specific)) options"
    fi
    if [ "$implicit_mode" != "" ]; then
        if [ "$mode" = "default" ]; then
            mode=$implicit_mode
        elif [ "$implicit_mode" != "$mode" ]; then
            error "Option(s) conflict with mode \"$mode\": $(delimit ', ' $parallel_specific $game_specific)"
        fi
    fi
}

check_mode () {
    local orig_mode exp_mode parallel_specific
    mode=${mode,,}
    if [ "$mode" = "" ]; then
        error 'Mode must be one of "parallel", "game" or "serial"'
    elif [ "$mode" != "default" ]; then
        exp_mode=$(match_prefix "$mode" parallel game serial)
        if [ "$exp_mode" = "" ]; then
            error 'Unknown mode "'"$mode"'"; use one of "parallel", "game" or "serial"'
        else
            mode=$exp_mode
        fi
    fi
    orig_mode=$mode
    check_mode_specific_opts
    if [ "$mode" = "game" ]; then
        if ! prog_available sbatch && [ "$dry_run" = "" ]; then
            error "SLURM (sbatch) not available"
        fi
    elif [ "$mode" = "parallel" ]; then
        if [ "$has_parallel" = "" ]; then
            if [ "$orig_mode" = "parallel" ]; then
                # If mode set explicitly, error
                error "Parallel not available"
            else
                # Mode inferred from options
                parallel_specific=$(delimit ', ' $(add_prefix '--' $opts_parallel))
                error "Parallel-specific options ($parallel_specific) used but Parallel not available"
            fi
        fi
    elif [ "$mode" = "default" ]; then
        if [ "$has_parallel" != "" ]; then
            mode="parallel"
        else
            # Fall back to serial
            warn "Parallel not available; falling back to serial mode"
            mode="serial"
        fi
    fi
}

run () {
    if [ "$dry_run" != "" ] || [ "$verbose" != "" ]; then
        echo_quoted "$@"
    fi
    if [ "$dry_run" = "" ] || [ "$mode" != "serial" ]; then
        "$@"
    fi
}

list_infiles () {
    local infile patt infile_base
    # The following replaces {} -> ${foo}, {%.*} -> ${foo%.*} and so on
    # TODO: Support escaping { by prepending a backslash
    patt=${outfile_pattern//\{/\$\{infile_base}
    echo_dbg "$patt"
    if [ "$force" = "" ]; then
        for infile in "$@"; do
            infile_base=$(basename $infile)
            if [ "$(eval "ls $outdir/$patt 2> /dev/null")" = "" ]; then
                safe_echo "$infile"
            elif [ "$verbose" != "" ]; then
                warn "Skipping input file \"$infile\": output file \"$outdir/$(eval echo "$patt")\" already exists"
            fi
        done
    else
        ls "$@"
    fi
}

run_parallel () {
    local infiles cmd
    infiles=$1
    cmd=$cmd_base
    cmd=${cmd//\{</\{}
    cmd=${cmd//\{.\*\}/\{%%\\.[^/]*\}}
    cmd=${cmd//\{\/.\*\}/\{= s:.*/([^./]+).*:\$1: =\}}
    cmd=${cmd//\{>\}/$outdir/\{/\}}
    cmd=${cmd//\{>.\}/$outdir/\{/.\}}
    cmd=${cmd//\{>..\}/$outdir/\{/..\}}
    cmd=${cmd//\{>.\*\}/$outdir/\{= s:.*/([^./]+).*:\$1: =\}}
    opts="--jobs $jobs --load $load $opts"
    [ "$dry_run" != "" ] &&
        opts="--dry-run $opts"
    [ "$verbose" != "" ] &&
        opts="--verbose $opts"
    # {%%} requires --plus
    echo "$infiles" |
        run parallel --plus $opts "$cmd"
}

replace_placeholders () {
    local cmd infile outfile
    cmd=$1
    infile=$2
    indir=$(dirname $infile)
    inbase=$(basename $infile)
    outfile=$outdir/$inbase
    cmd=${cmd//\{</\{}
    cmd=${cmd//\{\}/$infile}
    cmd=${cmd//\{.\}/$indir/${inbase%.*}}
    cmd=${cmd//\{..\}/$indir/${inbase%.*.*}}
    cmd=${cmd//\{.\*\}/$indir/${inbase%%.*}}
    cmd=${cmd//\{\/\}/$inbase}
    cmd=${cmd//\{\/.\}/${inbase%.*}}
    cmd=${cmd//\{\/..\}/${inbase%.*.*}}
    cmd=${cmd//\{\/.\*\}/${inbase%%.*}}
    cmd=${cmd//\{>\}/$outfile}
    cmd=${cmd//\{>.\}/$outdir/${inbase%.*}}
    cmd=${cmd//\{>..\}/$outdir/${inbase%%.*.*}}
    cmd=${cmd//\{>.\*\}/$outdir/${inbase%%.*}}
    safe_echo "$cmd"
}

# Output a value relative to the size of file fname ($1): the size (in
# bytes) divided by divisor ($2) but at least min ($3).
calc_rel_value () {
    local fname divisor min filesize result
    fname=$1
    divisor=$2
    min=$3
    filesize=$(get_filesize "$fname")
    # Calculate ceiling($filesize / $divisor)
    result=$((($filesize + $divisor - 1) / $divisor))
    if [ $result -lt $min ]; then
        result=$min
    fi
    echo $result
}

# Output the value of the divisor for an option argument that may
# specify a value relative to input file size in the form
# "value/divisor". full_val ($1) is the full argument value, base_val
# ($2) is the numeric value of the argument value base (quantity
# without divisor). If val has no slash and divisor, output 0. The
# divisor may have a suffix K, M or G for kibi-, mebi- or gibibytes;
# without a suffix, mebibytes are assumed. (Lower-case letters are
# also recognized.) Output the divisor in bytes divided by base_val,
# so that a value relative to the size of a file can be obtained by
# dividing the size (in bytes) by the divisor. If the divisor is
# invalid, output nothing and return 1.
get_divisor () {
    local full_val base_val
    # Convert to upper case for K, M, G
    full_val=${1^^}
    base_val=$2
    if [ "$full_val" = "${full_val#*/}" ]; then
        # No slash -> no divisor
        echo 0
        return 0
    else
        # val is the divisor part
        full_val=${full_val#*/}
    fi
    if ! is_int "${full_val%[KMG]}" || [ "${full_val%[KMG]}" -lt 1 ]; then
        # Invalid divisor
        return 1
    fi
    if [ "${full_val%K}" != "$full_val" ]; then
        full_val=$((${full_val%K} * 1024))
    elif [ "${full_val%G}" != "$full_val" ]; then
        full_val=$((${full_val%G} * 1024 * 1024 * 1024))
    else
        # Default to MiB
        full_val=$((${full_val%M} * 1024 * 1024))
    fi
    echo $(($full_val / $base_val))
    return 0
}

# Set the value of an option variable based on option argument value
# that can be either a single absolute value or of the form
# "value/divisor", making the value relative to input file size. value
# is numeric or can be converted to a numeric value, and divisor is a
# numeric value with an optional suffix K, M or G for kibi-, mebi- or
# gibibytes (without a suffix, M is assumed; lower-case letters are
# also recognized). If the value is an absolute value, it is assigned
# to option variable as is. If the value is relative, the option
# variable is assigned a command substitution calling function
# calc_rel_value (needs to be eval'ed).
#
# Arguments:
# - optname: option name (also option variable name)
# - val: option argument value
# - convert_func: function to convert the base value (without divisor)
#   to integer
set_opt_rel_value () {
    local optname val convert_func error_msg val_base divisor
    optname=$1
    val=$2
    convert_func=$3
    error_msg="Invalid argument for --$optname: \"$val\""
    val_base=$($convert_func ${val%/*})
    if [ "$val_base" = "" ]; then
        error "$error_msg"
    fi
    divisor=$(get_divisor "$val" $val_base)
    if [ "$divisor" = "" ]; then
        error "$error_msg"
    fi
    if [ "$divisor" != 0 ]; then
        eval "$optname='\$(calc_rel_value \$infile $divisor \$${optname}_min)'"
    else
        eval "$optname=$val_base"
    fi
}

# Ensure that the argument is a positive integer. If two arguments are
# given, the first one is a comparison operator for comparing the
# argument to 0.
ensure_pos_int () {
    local cmp val
    cmp=-gt
    if [ $# = 2 ]; then
        cmp=$1
        shift
    fi
    val=$1
    if is_int "$val" && [ "$val" $cmp 0 ]; then
        echo $val
    fi
}

# Output argument converted to mebibytes. The argument is a positive
# integer, optionally followed by M or m (mebibytes, the default if no
# suffix) or G or g (gibibytes). If the argument is invalid, output
# nothing.
convert_to_mib () {
    local val
    val=${1^^}
    if [ "${val%M}" != "$val" ]; then
        val=${val%M}
    elif [ "${val%G}" != "$val" ]; then
        val=$((${val%G} * 1024))
    fi
    ensure_pos_int "$val"
}

# Output argument converted to minutes. The argument can be either
# minutes (a positive integer) or of the form hh:mm. If the argument
# is invalid, output nothing.
convert_to_min () {
    local val
    val=$1
    if [ "${val%:*}" != "$val" ] && is_int "${val%:*}" &&
           is_int "${val#*:}";
    then
        # hh:mm
        val=$((${val%:*} * 60 + ${val#*:}))
    fi
    ensure_pos_int "$val"
}

process_game_opts () {
    set_opt_rel_value "memory" "$memory" convert_to_mib
    set_opt_rel_value "time" "$time" convert_to_min
    # --scratch argument may be 0, so test with "ensure_pos_int -ge"
    set_opt_rel_value "scratch" "$scratch" "ensure_pos_int -ge"
}

# Return true if $1 contains Parallel replacement strings. Note that
# this recognizes the replacement strings by the first character
# following the "{", so it does not work correctly if $1 contains such
# strings that are nevertheless not Parallel replacement strings.
contains_parallel_rpl () {
    [ "$1" != "${1#*\{[\}./#%0-9=+:#%^,]}" ]
}

run_game () {
    local infiles infile job_opt cmd_runner cmdline_suffix cmd
    infiles=$1
    process_game_opts
    opts="--minutes $time --MiB $memory --scratch $scratch --cores $cores $opts"
    [ "$dry_run" != "" ] &&
        opts="--cat $opts"
    if [ "$has_parallel" != "" ] &&
           contains_parallel_rpl "$(replace_placeholders "$cmd_base" @)";
    then
        cmd_runner="parallel --plus"
        # Actual value set below separately for each input file
        cmdline_suffix=":::"
    else
        cmd_runner="bash -c"
        cmdline_suffix=
    fi
    for infile in $infiles; do
        if [ ! -r "$infile" ]; then
            warn "Input file not found or inaccessible: $infile"
            continue
        fi
        cmd=$(replace_placeholders "$cmd_base" $infile)
        job_opt="--job $outdir-${infile%%.*}"
        if [ "$cmdline_suffix" != "" ]; then
            cmdline_suffix="::: '$infile'"
        fi
        # Use eval to expand the possible command substitutions in
        # $opts ($time, $memory and $scratch)
        eval "run $game $opts $job_opt $cmd_runner \"$cmd\" $cmdline_suffix"
    done
}

run_serial () {
    infiles=$1
    for infile in $infiles; do
        if [ ! -r "$infile" ]; then
            warn "Input file not found or inaccessible: $infile"
            continue
        fi
        cmd=$(replace_placeholders "$cmd_base" $infile)
        run bash -c "$cmd"
    done
}

main () {
    local infiles
    if [ $# -lt 3 ]; then
        error "Output directory, command and at least one input file required"
    fi
    outdir=$1
    cmd_base=$2
    shift 2
    check_outdir
    check_mode
    infiles=$(list_infiles "$@")
    if [ "$infiles" != "" ]; then
        eval "run_$mode \"$infiles\""
    elif [ "$verbose" != "" ]; then
        warn "All output files already exist; use --force to overwrite"
    fi
}


main "$@"
