#! /bin/bash

# multirun
#
# Run a processing command for multiple input files, possibly in
# parallel with the help of GNU Parallel or SLURM via game.

# TODO:
# - Handle subdirectories in the input: at least make
#   --output-file-pattern work with them.


progname=`basename $0`
progdir=`dirname $0`

usage_header="Usage: $progname [options] outdir \"command\" infiles ...

Run a processing command for multiple input files infiles, producing
output to output directory outdir, typically one output file
corresponding to one input file, possibly in parallel with the help of
GNU Parallel or SLURM via game.

command is a single string containing a complete command line with a
command and arguments. command is evaluated by the shell, so it can be
composed of multiple commands, use I/O redirection and pipes.

In the command line, the following strings are replaced with input or
output file names: {<} -> input file name, {>} -> output file name,
{<.} -> input file name without extensions, {>.} -> output file name
without extensions. When using Parallel, its replacement strings are
also replaced (including the additional ones added by the --plus
option)."

optspecs='
m|mode=MODE "default"
    Run command using MODE: one of "parallel" (use GNU Parallel),
    "game" (use SLURM via game) or "serial" (run serially); any prefix
    of the mode name is also recognized (default: "parallel" if
    Parallel is available, otherwise "serial").
output-file-pattern=PATTERN "{}" outfile_pattern
    If PATTERN matches any files in the output directory for an input
    file, do not run command for the input file. "{}" in PATTERN
    refers to the base name of the input file (without directories).
    Bash string operations can also be used to modify the base name of
    the input file: for example, "{%.*}" is the file name with the
    (last) extension removed and "{##*.}" is the last extension.
    Shell wildcards in PATTERN are expanded. NOTE that this option
    only specifies the files whose existence is to be checked for each
    input file; the names of the actual output files are determined by
    command. (Default: %(default)s.)
options=OPTS opts
    Pass OPTS as options to Parallel or game.
f|force
    Run the command even if the output file exists.
v|verbose
    Output the commands to be run.
n|dry-run
    Do not actually run commands; only show what is to be run.
'

. $progdir/korp-lib.sh


# Process options
eval "$optinfo_opt_handler"

game=$progdir/../vrt-tools/game


check_outdir () {
    if [ ! -d "$outdir" ]; then
        if [ -e "$outdir" ]; then
            error "$outdir exists but is not a directory"
        fi
        if [ "$dry_run" = "" ]; then
            mkdir "$outdir"
        fi
    fi
}

check_mode () {
    mode=${mode,,}
    if str_hasprefix "parallel" "$mode" || [ "$mode" = "default" ]; then
        if prog_available parallel; then
            mode="parallel"
        elif [ "$mode" = "default" ]; then
            # If mode not set explicitly, fall back to serial
            warn "parallel not available; falling back to serial mode"
            mode="serial"
        else
            # If mode set explicitly, error
            error "parallel not available"
        fi
    elif str_hasprefix "game" "$mode"; then
        if prog_available sbatch || [ "$dry_run" != "" ]; then
            mode="game"
        else
            error "SLURM (sbatch) not available"
        fi
    elif str_hasprefix "serial" "$mode"; then
        mode="serial"
    else
        error 'Unknown mode "'"$mode"'"; use one of "parallel", "game" or "serial"'
    fi
}

run () {
    if [ "$dry_run" != "" ] || [ "$verbose" != "" ]; then
        echo_quoted "$@"
    fi
    if [ "$dry_run" = "" ] || [ "$mode" != "serial" ]; then
        "$@"
    fi
}

list_infiles () {
    local infile patt infile_base
    # The following replaces {} -> ${foo}, {%.*} -> ${foo%.*} and so on
    # TODO: Support escaping { by prepending a backslash
    patt=${outfile_pattern//\{/\$\{infile_base}
    echo_dbg "$patt"
    if [ "$force" = "" ]; then
        for infile in "$@"; do
            infile_base=$(basename $infile)
            if [ "$(eval "ls $outdir/$patt 2> /dev/null")" = "" ]; then
                safe_echo "$infile"
            fi
        done
    else
        ls "$@"
    fi
}

run_parallel () {
    local infiles cmd
    infiles=$1
    cmd=$cmd_base
    cmd=${cmd//\{<\}/\{\}}
    cmd=${cmd//\{>\}/$outdir/\{/\}}
    cmd=${cmd//\{<.\}/\{%%\\..*\}}
    cmd=${cmd//\{>.\}/$outdir/\{%%\\..*\}}
    [ "$dry_run" != "" ] &&
        opts="--dry-run $opts"
    [ "$verbose" != "" ] &&
        opts="--verbose $opts"
    # {%%} requires --plus
    echo "$infiles" |
        run parallel --plus $opts "$cmd"
}

replace_placeholders () {
    local cmd infile infile_noext outfile outfile_noext
    cmd=$1
    infile=$2
    infile_noext=${infile%%.*}
    outfile=$outdir/$(basename $infile)
    outfile_noext=${outfile%%.*}
    cmd=${cmd//\{<\}/$infile}
    cmd=${cmd//\{>\}/$outfile}
    cmd=${cmd//\{<.\}/$infile_noext}
    cmd=${cmd//\{>.\}/$outfile_noext}
    safe_echo "$cmd"
}

run_game () {
    local infiles infile job_opt cmd
    infiles=$1
    [ "$dry_run" != "" ] &&
        opts="--cat $opts"
    for infile in $infiles; do
        cmd=$(replace_placeholders "$cmd_base" $infile)
        job_opt="--job $outdir-${infile%%.*}"
        run $game $opts $job_opt bash -c "$cmd"
    done
}

run_serial () {
    infiles=$1
    for infile in $infiles; do
        cmd=$(replace_placeholders "$cmd_base" $infile)
        run bash -c "$cmd"
    done
}

main () {
    local infiles
    if [ $# -lt 3 ]; then
        error "Output directory, command and at least one input file required"
    fi
    outdir=$1
    cmd_base=$2
    shift 2
    check_outdir
    check_mode
    infiles=$(list_infiles "$@")
    if [ "$infiles" != "" ]; then
        eval "run_$mode \"$infiles\""
    elif [ "$verbose" != "" ]; then
        warn "All output files already exist; use --force to overwrite"
    fi
}


main "$@"
