[
    ElemRule(ElemCond('*'),
             target=ElemTargetSkip(ElemContent('*'))),
    ElemRule(ElemCond('w'),
             target=ElemTargetVrt([ElemTargetVrtTextField(0, {'strip': True}),
                                   ElemTargetVrtAttrField(['lemma', 'pos',
                                                           'mrp', 'fun'])])),
    ElemRule(ElemCond('pu'),
             target=ElemTargetVrt([ElemTargetVrtTextField([0, 0]),
                                   ElemTargetVrtConstField(['punct', '', ''])])),
    ElemRule(ElemCond('cl'),
             target=ElemTargetElem('clause',
                                   [ElemAttrCopy(['num', 'type', 'hier', 'snum',
                                                  'sinum', 'clnum',
                                                  'hallnum'])],
                                   ElemContent('*'))),
    ElemRule(ElemCond('s'),
             target=ElemTargetElem('sentence',
                                   [ElemAttrId('id'),
                                    ElemAttrCopy(['num', 'wnum', 'clnum',
                                                  'source', 'sp', 'sinum'])],
                                   ElemContent('*'))),
    ElemRule(ElemCond('p'),
             target=ElemTargetElem('paragraph',
                                   [ElemAttrCopy(['id', 'type', 'n'])],
                                   ElemContent('*'))),
    ElemRule(ElemCond('korpusla'),
             target=ElemTargetElem('text',
                                   [ElemAttrContentText('header', 'header'),
                                    ElemAttrContentText('info', 'info')],
                                   ElemContent('*')))
]
